filter:
    excluded_paths: [tests/*, vendor/*]

build:
    nodes:
        analysis:
            tests:
                override: [php-scrutinizer-run]
        coverage:
            tests:
                override:
                    - command: ./vendor/bin/phpunit --coverage-clover coverage/clover.xml
                      coverage:
                          file: coverage/clover.xml
                          format: clover
