language: php
php:
    - 7.2
    - 7.3
    - 7.4
env:
    matrix:
        - COMPOSER_FLAGS="--prefer-lowest"
        - COMPOSER_FLAGS=""
    global:
        - secure: m2YpS1N8rAi+NVpmULPTFTKFgoLVZEWuxbyzvMdjS0hq1sC3gBwuJfOjoPjalG0d6vVFt806X2VOAC9Mjll+HXkZ37WIGFsARHERr9XUyhv8Uzv4q8eCFqehyGAuFuPB/3xkK3bxlUAw/B78Fu+WLojspwPwtfyzA8zEUlv77Yws1RZlhjnzgvnhEg/SOtuo1Jy7xBGUKbecDOhfs9sXkfYu1qCFJyuaIvlXDz9hiSgiXlC/yc4/3Pn1lCJJyFxG0EMMwq18frG6+L9lv9QjWO/QABV37rVFP2xazqAlbdGzPcdbi+LUy9eJiHxZf4zKag7nhpWuKg8yxovWJj4p+GvlwrvLTunXtUic5AgRNRLsafYLlYR2nthF9330iSEfeoGMnipQL01avUKmtLvznxg37823Jb5enPRDxzZoInGweGFCsDeU2XyHC15Vr5d+FliJfUqt8nnHe6oN46r5YEuwXKcNXd5x53nwcoK78E9Q0bmU1J9JiABBMTc+DwOeUe4YQ+Xbc5xios4NlLKuJMYxYCIm3OKCDQdXXnpYooNM2ToPa8VeR1l+ZTZCcLB6/cJHZ3iHcUQCLma3iFK4P3yzASvNnA4ECJFHDPF1xRwufuvyIDhtFV4fKrZIVbr3FTaxY8vtw72VHFIeSlFYslUMvuXn4+jup1zBDj39okc=
        - secure: kYAcaHCm14ktU4RrhOCIpZ/1E+ZoYnwYnNhEXt6TXQnAB0nTHBf8JaAnJx6JFvappd6OD9dpBpHuT1tgYP4szUAWveexhh/KR8s4zDv05rMUgHcp4Uw38FwlgNV42jkImVNNBqCei8JnjzARZoOGGgBf9U2uMYwPPLk7uCAgE/l3HRlAjKONouOkcLqPt1khO8jovrkRQnGRwFf92jOGNV+M1RFKlfY42EEdekSC2RgrcUQLnZxFM2il03OF1Lzh87X4cfJo0LlrIBL2x04JW/2hFvWp8PjefrpDzoG5MTjLjH6pHmLF6LHEn8sGUZbsOrW3vaC7BECw1pyyPtJ/Qu5cSfxvVhCSTWZoLSAo9wwrf4CKJ3dnLcwDsZP24BDMGHqb8gzRHoOdrSYzDwP6fQCy1L4J66sCM2dxZCr0DL3DOrZG4+F/Z4gaf4hPDD+0Hk9T6vuVTUKQiX81FPX6gOtpqXNtBkNdowSWRbZdZk23XtOlbL5PF4pAmlR7i8q2S0TbxO9zycVrirletbYSQ0poVDNnqES0VSpZ8N+CDzNsNWHhjGnxLim/y4qQx45vr04KTlF3dntBtoVIncNXvPoffw3LyJ47A8v1zDXkst7mL+tB5++2MNSlL7dw8/lWNYGdp/LLFpvaNst7ZcC7Im0eSGusBNtWkX+ssGxbZv4=
install:
    - echo "{\"http-basic\":{\"nova.laravel.com\":{\"username\":\"${NOVA_USERNAME}\",\"password\":\"${NOVA_PASSWORD}\"}}}" > auth.json
before_script:
    - travis_retry composer self-update
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
script:
    - vendor/bin/phpunit
