language: php
php:
    - 7.3
    - 7.4
env:
    matrix:
        - COMPOSER_FLAGS="--prefer-lowest"
        - COMPOSER_FLAGS=""
    global:
        - secure: m2YpS1N8rAi+NVpmULPTFTKFgoLVZEWuxbyzvMdjS0hq1sC3gBwuJfOjoPjalG0d6vVFt806X2VOAC9Mjll+HXkZ37WIGFsARHERr9XUyhv8Uzv4q8eCFqehyGAuFuPB/3xkK3bxlUAw/B78Fu+WLojspwPwtfyzA8zEUlv77Yws1RZlhjnzgvnhEg/SOtuo1Jy7xBGUKbecDOhfs9sXkfYu1qCFJyuaIvlXDz9hiSgiXlC/yc4/3Pn1lCJJyFxG0EMMwq18frG6+L9lv9QjWO/QABV37rVFP2xazqAlbdGzPcdbi+LUy9eJiHxZf4zKag7nhpWuKg8yxovWJj4p+GvlwrvLTunXtUic5AgRNRLsafYLlYR2nthF9330iSEfeoGMnipQL01avUKmtLvznxg37823Jb5enPRDxzZoInGweGFCsDeU2XyHC15Vr5d+FliJfUqt8nnHe6oN46r5YEuwXKcNXd5x53nwcoK78E9Q0bmU1J9JiABBMTc+DwOeUe4YQ+Xbc5xios4NlLKuJMYxYCIm3OKCDQdXXnpYooNM2ToPa8VeR1l+ZTZCcLB6/cJHZ3iHcUQCLma3iFK4P3yzASvNnA4ECJFHDPF1xRwufuvyIDhtFV4fKrZIVbr3FTaxY8vtw72VHFIeSlFYslUMvuXn4+jup1zBDj39okc=
        - secure: UBWRP8nylocww6j15ZyRmDwFRb20vmVvJsNNjeiPO91kzHEvWEuadVroiISpkI05zpcV3dXS91ISjN4rTQvm6GA0sRgRZQAx8I2QqKYqbef4asd8qNB/2Pd1X8CYzsNGePs4u315mSonA7453XrIaQVQ/ejANaMBSeaVvpeNTtHi7aybjDQwcXtAWsM1N+QgHv/ltj+VgDPm4tlfHInqHgtsnefTmVvU4OsRViTXe/ReX9qOXZ7ykdRfguDLVC7scy436y+hRcCNuct/89B83U++1VkEgt8pa84/2Py59w765C8pKySkIeHzuU8phVqMDaO6z9a1jz0IBhb2SSV329dVT7HxGIRLRkZSwOsY3iShMGALuI2fITchQjXXXuu+8Cv7ZLZrzDIA/bXuXHxvMvxTpWnPi36Vl+YTv+T4KSE+pEaMmYviAlo13x2fHCSFGu4lZJERoKJXWzbBpSyrylzUTYOK/BGWOm4oUxHV+Xx3Z7okmkQJCGoKszWQ/9/CeQf1a5IahonB+B+v+HDJKxPddfkF+02fAD8Eww7c7Z8CXMvnsnoUiMXXx1BykALXUQwg1OmwKrVm2X+PtQdhQiRmMUqQ2AxYMgJ8CWaGpeKREj7gO6rv6G1copZI+GQo3d0uohncGySrufYIbbvZ/B8ykNQFnv9yjQHUltmO9ao=
install:
    - echo "{\"http-basic\":{\"nova.laravel.com\":{\"username\":\"${NOVA_USERNAME}\",\"password\":\"${NOVA_PASSWORD}\"}}}" > auth.json
before_script:
    - travis_retry composer self-update
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
script:
    - vendor/bin/phpunit
